server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/turtletrade
    username: turtle
    password: Zr@130805
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
